package com.cs407_android.ormlab;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.cs407_android.ormlab.AnEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table AN_EVENT.
*/
public class AnEventDao extends AbstractDao<AnEvent, Long> {

    public static final String TABLENAME = "AN_EVENT";

    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Location = new Property(2, String.class, "location", false, "LOCATION");
        public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
        public final static Property Day = new Property(4, Integer.class, "day", false, "DAY");
        public final static Property Month = new Property(5, Integer.class, "month", false, "MONTH");
        public final static Property Year = new Property(6, Integer.class, "year", false, "YEAR");
        public final static Property Display = new Property(7, Boolean.class, "display", false, "DISPLAY");
    };


    public AnEventDao(DaoConfig config) {
        super(config);
    }
    
    public AnEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'AN_EVENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'LOCATION' TEXT," + // 2: location
                "'DESCRIPTION' TEXT," + // 3: description
                "'DAY' INTEGER," + // 4: day
                "'MONTH' INTEGER," + // 5: month
                "'YEAR' INTEGER," + // 6: year
                "'DISPLAY' INTEGER);"; // 7: display
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'AN_EVENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AnEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(3, location);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
 
        Integer day = entity.getDay();
        if (day != null) {
            stmt.bindLong(5, day);
        }
 
        Integer month = entity.getMonth();
        if (month != null) {
            stmt.bindLong(6, month);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(7, year);
        }
 
        Boolean display = entity.getDisplay();
        if (display != null) {
            stmt.bindLong(8, display ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AnEvent readEntity(Cursor cursor, int offset) {
        AnEvent entity = new AnEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // location
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // day
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // month
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // year
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0 // display
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AnEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLocation(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDay(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setMonth(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setYear(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setDisplay(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected Long updateKeyAfterInsert(AnEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AnEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
