package com.cs407_android.ormlab;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.cs407_android.ormlab.AnEvent;

import com.cs407_android.ormlab.AnEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig anEventDaoConfig;

    private final AnEventDao anEventDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        anEventDaoConfig = daoConfigMap.get(AnEventDao.class).clone();
        anEventDaoConfig.initIdentityScope(type);

        anEventDao = new AnEventDao(anEventDaoConfig, this);

        registerDao(AnEvent.class, anEventDao);
    }
    
    public void clear() {
        anEventDaoConfig.getIdentityScope().clear();
    }

    public AnEventDao getAnEventDao() {
        return anEventDao;
    }

}
